name: Lint Terraform Configuration

description: A composite action for linting Terraform configuration.

inputs:
  terraform-version:
    description: The version of Terraform to use when running `terraform fmt` and `tflint`.
    required: false
    default: 1.14.3
  tflint-version:
    description: The version of TFLint to use when running `tflint`.
    default: 0.60.0
    required: false
  hcp-terraform-hostname:
    description: The hostname of the HCP Terraform organization used to source modules.
    default: app.terraform.io
    required: false
  hcp-terraform-api-token:
    description: The API token used to lint Terraform modules in a Private Module Registry.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Check Terraform Formatting
      run: |-
        terraform fmt -recursive -check
      shell: sh

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v6
      with:
        tflint_version: v${{ inputs.tflint-version }}

    - name: Export HCP Terraform Token
      if: inputs.hcp-terraform-api-token
      run: ${{ github.action_path }}/src/export_hcp_terraform_token.sh
      shell: sh
      env:
        HCP_TERRAFORM_HOSTNAME: ${{ inputs.hcp-terraform-hostname }}
        HCP_TERRAFORM_API_TOKEN: ${{ inputs.hcp-terraform-api-token }}

    - name: Lint Terraform Files
      run: |-
        terraform init -backend=false
        tflint --init
        tflint --recursive --format=compact
      shell: sh
